apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-patch-role
  namespace: buildkite
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - patch
      - update
