# Source: agent-stack-k8s/templates/config.yaml.tpl
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-stack-k8s-config
  namespace: buildkite
data:
  config.yaml: |
    agent-token-secret: agent-stack-k8s-secrets
    namespace: buildkite
    cluster-uuid: c338c74e-985e-4345-948e-fe530a7e1184
    debug: false
    default-checkout-params:
      envFrom:
      - configMapRef:
          name: agent-stack-k8s-env-vars-config
    default-command-params:
      envFrom:
      - configMapRef:
          name: agent-stack-k8s-env-vars-config
    image: ghcr.io/buildkite/agent@sha256:1f7733f0da24de76004d2ec3352c7984d30180590f595825d5ba65e080d40a22
    image-pull-backoff-grace-period: 60s
    job-ttl: 5m
    max-in-flight: 100
    org: moc-test
    pod-spec-patch:
      containers:
      - name: agent
      - name: checkout
      - name: container-0
        image: quay.io/dtrifiro/buildkite-toolchain:latest
        imagePullPolicy: Always
        workingDir: /tmp/
      initContainers:
      - name: copy-agent
    poll-interval: 5s
    prohibit-kubernetes-plugin: true
    tags:
    - queue=default
    - priority=high
