\# Source: agent-stack-k8s/templates/config.yaml.tpl
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-stack-k8s-config-vllm-image
  namespace: buildkite
data:
  config.yaml: |
    agent-token-secret: agent-stack-k8s-secrets
    namespace: buildkite
    cluster-uuid: 2ec33b8f-cb1b-4bb0-bdf8-d0f44ec6ea2b
    debug: false
    default-checkout-params:
      envFrom:
      - configMapRef:
          name: agent-stack-k8s-env-vars-config
    default-command-params:
      envFrom:
      - configMapRef:
          name: agent-stack-k8s-env-vars-config
    image: quay.io/tsalawu0/buildkite-runner:latest
    image-pull-backoff-grace-period: 60s
    job-ttl: 5m
    max-in-flight: 100
    org: test-org2-5
    pod-spec-patch:
      containers:
      - name: agent
      - name: checkout
      - name: container-0
        image: image-registry.openshift-image-registry.svc:5000/buildkite/vllm-main-test:latest
      initContainers:
      - name: copy-agent
    poll-interval: 5s
    prohibit-kubernetes-plugin: true
    tags:
    - queue=vllm-image
    - priority=high
