\# Source: agent-stack-k8s/templates/config.yaml.tpl
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-stack-k8s-config-vllm-image
  namespace: buildkite-vllm
data:
  config.yaml: |
    agent-token-secret: agent-stack-k8s-secrets
    namespace: buildkite-vllm
    cluster-uuid: 9cecc6b1-94cd-43d1-a256-ab438083f4f5
    debug: false
    default-checkout-params:
      envFrom:
      - configMapRef:
          name: agent-stack-k8s-env-vars-config
    default-command-params:
      envFrom:
      - configMapRef:
          name: agent-stack-k8s-env-vars-config
    image: ghcr.io/buildkite/agent:3.87.1
    image-pull-backoff-grace-period: 60s
    job-ttl: 5m
    max-in-flight: 100
    org: vllm
    pod-spec-patch:
      nodeSelector:
        nvidia.com/gpu.product: NVIDIA-A100-SXM4-40GB
      containers:
      - name: agent
      - name: checkout
      - name: container-0
        resources:
          limits:
            cpu: "15"
            memory: 200Gi
            nvidia.com/gpu: "2"
          requests:
            cpu: "10"
            memory: 100Gi
            nvidia.com/gpu: "2"
      initContainers:
      - name: copy-agent
    poll-interval: 5s
    prohibit-kubernetes-plugin: true
    tags:
    - queue=moc-a100
    - priority=high
