# Source: agent-stack-k8s/templates/secrets.yaml.tpl
# A sample agent token and graphql token secret
apiVersion: v1
kind: Secret
metadata:
  name: agent-stack-k8s-secrets
  namespace: buildkite
stringData:
  BUILDKITE_AGENT_TOKEN:
  BUILDKITE_TOKEN:
