apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: vllm-main-buildconfig
  namespace: buildkite
spec:
  source:
    type: Git
    git:
      uri: "https://github.com/tssala23/vllm.git"
      ref: "test"  # Use the branch that contains your Dockerfile
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile # Path to Dockerfile relative to repo root
  output:
    to:
      kind: ImageStreamTag
      name: "vllm-main-test:latest"  # Tag of the resulting image
  triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secretReference:
          name: webhook-secret  # Optional, for GitHub webhooks
