# Source: agent-stack-k8s/templates/rbac.yaml.tpl
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agent-stack-k8s
  namespace: buildkite-vllm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: agent-stack-k8s-controller
subjects:
  - kind: ServiceAccount
    name: agent-stack-k8s-controller
    namespace: buildkite-vllm
