apiVersion: image.openshift.io/v1
kind: ImageStreamImport
metadata:
  name: nvidia-cuda
  namespace: buildkite
spec:
  import: true
  images:
    - from:
        kind: DockerImage
        name: quay.io/tsalawu0/nvidia/cuda:12.4.1-devel-ubuntu20.04  # Source image
      to:
        name: 12.4.1-devel-ubuntu20.04  # Tag in ImageStream
      importPolicy:
        scheduled: true
