apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: build-access-binding
  namespace: buildkite
subjects:
  - kind: ServiceAccount
    name: default
    namespace: buildkite
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: build-access
